/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bg: "rgb(var(--canvas) / <alpha-value>)",
        panel: "rgb(var(--surface) / <alpha-value>)",
        elevated: "rgb(var(--surface-elevated) / <alpha-value>)",
        card: "rgb(var(--surface-card) / <alpha-value>)",
        light: "rgb(var(--surface-elevated) / <alpha-value>)",
        paper: "rgb(var(--surface-card) / <alpha-value>)",
        border: "rgb(var(--hairline) / <alpha-value>)",
        hairline: "rgb(var(--hairline) / <alpha-value>)",
        hairlineSoft: "var(--hairline-soft)",
        hairlineStrong: "var(--hairline-strong)",
        text: "rgb(var(--ink) / <alpha-value>)",
        ink: "rgb(var(--ink) / <alpha-value>)",
        inkSoft: "rgb(var(--charcoal) / <alpha-value>)",
        body: "rgb(var(--body) / <alpha-value>)",
        muted: "rgb(var(--mute) / <alpha-value>)",
        ash: "rgb(var(--ash) / <alpha-value>)",
        stone: "rgb(var(--stone) / <alpha-value>)",
        onPrimary: "rgb(var(--on-primary) / <alpha-value>)",
        onDarkMute: "var(--on-dark-mute)",
        primary: "rgb(var(--primary) / <alpha-value>)",
        primaryPressed: "rgb(var(--primary-pressed) / <alpha-value>)",
        accent: "rgb(var(--accent-red) / <alpha-value>)",
        accent2: "rgb(var(--accent-blue) / <alpha-value>)",
        accentBlue: "rgb(var(--accent-blue) / <alpha-value>)",
        accentBlueSoft: "var(--accent-blue-soft)",
        accentRed: "rgb(var(--accent-red) / <alpha-value>)",
        accentRedSoft: "var(--accent-red-soft)",
        accentGreen: "rgb(var(--accent-green) / <alpha-value>)",
        accentGreenSoft: "var(--accent-green-soft)",
        accentYellow: "rgb(var(--accent-yellow) / <alpha-value>)",
        accentYellowSoft: "var(--accent-yellow-soft)",
        ok: "rgb(var(--accent-green) / <alpha-value>)",
        warn: "rgb(var(--accent-yellow) / <alpha-value>)",
        err: "rgb(var(--accent-red) / <alpha-value>)",
      },
      fontFamily: {
        sans: ["'Inter'", "ui-sans-serif", "system-ui", "sans-serif"],
        display: ["'Inter'", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["'Inter'", "ui-sans-serif", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};
